### ISSUE TITLE
Use measured distance from distance sensor to determine accuracy

### ISSUE THREAD

**Issue by derfinke** [derfinke/Sailwind_Projekt#48]
Use the distance from distance sensor to determine accuracy and move the motor in case of a bigger delta then defined.
Distance has to be taken during calibration and after hitting the frin endwitch the distance must be saved to get the absolute distance value.

**Comment by BeneHTWG** [comment]
fixed in #62: now distance is converted properly to relative distance by capturing the absolute start point when hitting the front endswitch
also when a delta of 10mm is reacched, a direct partial recover is triggered in the Localization
