### ISSUE TITLE
Save position after approaching a certain trim or roll percentage

### ISSUE THREAD

**Issue by derfinke** [derfinke/Sailwind_Projekt#51]

**Comment by BeneHTWG** [comment]
currently the position is safed allways after every position change

**Comment by BeneHTWG** [comment]
**update**: localization is now safed after movement has changed

- movement is additionally safed in FRAM
- depending on last movement before shutdown, the last safed position can be assumed as correct or not
- if not, the deserialization is stated as partial recovery which leads to a shortened localization process (still initialized as usual)
   where the linear guide only drives to the front end to reset the pulse count to 0 -> Localization is correct again

- if the deserialization fails or the Localization was canceled by the shutdown, the Localization must be processed normally
