### ISSUE TITLE
Besprechung 02.10.23

### ISSUE THREAD

**Issue by derfinke** [derfinke/Sailwind_Projekt#85]
1. position trimmen rollen + und -

2. Manuelles fahren position merken und anfahren

3. Motorimpulse als referenz wert des Abstandes

4. Abstandswert wird bei zu großem delta als warnung ausgegeben

5. wechselschalter betrieb für automatik manuell

6. DHCP checkbox

7. IP addresse manuell zurücksetzen

**Comment by BeneHTWG** [comment]
- the functions [get / set]_[current / desired]_roll_trim_percentage now [return / pass] the percentage as positive or negative value depending on trim or roll mode (1)
- this is already changed in #34, the REST module and in the webserver / ssi_handler but not tested yet @derfinke 
- the features (2)...(5) are implemented and tested
- (6) is not done yet
- for (7) the Reset is triggered in longpress callback from Manual Control when both move buttons are pressed for 10 s. Also the ip is now updated in mx_lwip_init and in tcp Server init by an FRAM read call

**Comment by BeneHTWG** [comment]
**additional features**

- localization is now safed to FRAM on each position change -> automatic mode on reboot allways possible
- a direct change between forward and backwards is now avoided by queueing the requests, and finishing the brake phase before
- also a brake phase can now be interrupted directly by an acceleration into the current direction
- when setting the center from webserver, the led blinks now as well as with the physical button
- the blink function now Starts a periodic timer that toggles the led every 200 ms in the callback, which Stops After 9 toggles with a specific Final led state
